### ISSUE TITLE
Missing files ?

### ISSUE THREAD

**Issue by Spheerys** [Jako/SuperBoxFontawesome#1]
Hi !

I have installed the transport package manually without problem and followed the instruction to use this addon, but when I try to use it on a TVs, the list is empty.
After anabling debug mode on SuperBoxSelect, I have found this error : 
```
[2018-05-14 11:58:35] (ERROR @ /home/user/web/website.org/public_html/core/model/modx/modx.class.php : 1706) Processor /home/user/web/website.org/public_html/core/components/superboxfontawesome/processors/types/resources/getlist.php does not exist; Array
(
    [processors_path] => /home/user/web/website.org/public_html/core/components/superboxfontawesome/processors/
    [location] => 
    [action] => types/resources/getlist
)
```
It's look like at least a file is missing : /core/components/superboxfontawesome/processors/types/resources/getlist.php

What did I miss ?

**Comment by Jako** [comment]
Have you installed both packages (SuperBoxSelect + SuperBoxFontawesome)?

**Comment by Spheerys** [comment]
yes of course.

**Comment by Jako** [comment]
Did you save and reload the template variable and set the Type to `FontAwesome Icons`?

**Comment by Jako** [comment]
It should request the list from `/core/components/superboxfontawesome/processors/types/fontawesome/getlist.php`

**Comment by Spheerys** [comment]
There is my TV setting :  https://screenshots.firefox.com/TbezOs3LTsF8PR1X/lesouriant.org

**Comment by Jako** [comment]
The value in Type looks wrong. Is this a dropdown select? Could you select `FontAwesome Icons` there?

**Comment by Spheerys** [comment]
No I can't : I can only select Resource or User

**Comment by Jako** [comment]
Please reload the manager, after you have saved the vemplate variable with the new package setting. Then the type dropdown will have different values. I have done the reload, when the screen gets white in the following screencast.

![howto](https://user-images.githubusercontent.com/148371/40041996-26481b82-5820-11e8-92e1-2f9492c621a1.gif)

**Comment by Jako** [comment]
I would prefer to change the type dropdown (without a reload by ExtJS) when the package is changed, but this is not that trivial.

**Comment by Spheerys** [comment]
Yes I did this with success by following your demo ! Thanks !
But I now have another issue : the TV's still doesn't work because this error : 
```
[2018-05-16 13:15:55] (ERROR in superboxselect.fontawesome @ /home/User/web/website.org/public_html/core/components/superboxfontawesome/processors/types/fontawesome/getlist.class.php : 82) Could not find the icons in the FontAwesome scss!
```

I thought FontAwesome font was loading natively by MODX Manager....
How can I load it to make this works ?

**Comment by Jako** [comment]
It uses/parses `https://raw.githubusercontent.com/FortAwesome/Font-Awesome/master/scss/_icons.scss` per default which seems to be not available anymore.

You could create a system setting `superboxselect.fontawesomeUrl` and set this to `https://raw.githubusercontent.com/FortAwesome/Font-Awesome/fa-4/scss/_icons.scss` or patch the url in line 16 of `core/components/superboxfontawesome/processors/types/fontawesome/getlist.class.php`

**Comment by Spheerys** [comment]
Yes it's works like a charm now !
Thank you very much !!

**Comment by Jako** [comment]
If you want to use this with FontAwesome 5, you have to change the url to i.e. `https://raw.githubusercontent.com/FortAwesome/Font-Awesome/master/web-fonts-with-css/scss/_icons.scss`

I hope the regex works with that.

**Comment by Spheerys** [comment]
It's nearly working with V5
Have a look here : https://i.imgur.com/z1dbQzl.png
Not all the icons are here.
In my case, the V4 version is enough :)

**Comment by Jako** [comment]
With version 5, you additionally have to load the FontAwesome 5 CSS in the manager. But that will create some manager style issues and it can't be done in the getlist processor of this package.
