### ISSUE TITLE
fontawesome compatibility

### ISSUE THREAD

**Issue by patrickatwsrn** [Jako/SuperBoxFontawesome#3]
Seems the current version is only compatible with version 4.x because the structure of icons.scss has been changed at some point the the past. 

As the link to the default repository at https://raw.githubusercontent.com/FortAwesome/Font-Awesome/fa-4/scss/_icons.scss isn't available anymore, I recommend to download the latest version from fontawesome.com and install it locally (this also solves potential privacy issues...)

The latest 4.x version can be downloaded here: https://fontawesome.com/v4/assets/font-awesome-4.7.0.zip

Upload it into assets directory and add the full path of  _icons.scss file to your fontawesome url settings.

Example: 

```
https://example.com/assets/fonts/fontAwesome_v4.x/scss/_icons.scss
```

**Comment by Jako** [comment]
The branch was renamed: https://raw.githubusercontent.com/FortAwesome/Font-Awesome/4.x/scss/_icons.scss
