### ISSUE TITLE
UI issues

### ISSUE THREAD

**Issue by patrickatwsrn** [Jako/SuperBoxFontawesome#4]
# Just a list of thing that I have noticed

## Prefix missing from selection

I can select an icon from the list and in return I see the name of the icon (without the fa- prefix). 

<img width="638" alt="image" src="https://user-images.githubusercontent.com/68318893/233150083-1a659535-9717-48ad-a31c-b3e93219cf7e.png">

## Searching for an icon requires the full icon name including prefix

Typing the name of an icon only returns a result if it is prefixed AND complete

<img width="623" alt="image" src="https://user-images.githubusercontent.com/68318893/233150335-dc74b46f-1bb0-4f32-890b-94af201d2c15.png">

<img width="642" alt="image" src="https://user-images.githubusercontent.com/68318893/233150378-1e1781cc-7913-410d-a4d5-0a84f6dfda6a.png">

## Filter doesn't work

Searching for an icon should filter the number of results

<img width="640" alt="image" src="https://user-images.githubusercontent.com/68318893/233151615-9feb04c0-e302-4089-9bd7-d687f5b9b6fd.png">

Cheers,

Patrick

**Comment by Jako** [comment]
The search issues will be solved in the next release. The display issue can't be solved that easy: https://stackoverflow.com/questions/24998486/extjs-3-4-combobox-keep-value-format-after-selection/25005162#25005162 - 1/ is not possible because of HTML in the value. 2/ would touch other types.
